CONFIG_ZMK_KEYBOARD_NAME="Planck Rev6"

# Force USB execution and disable BLE features
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=n

# Turn off sleep modes (unnecessary for wired keyboards)
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_TIMEOUT=0
# Reduce typing latency while preventing chatter
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Combo config, automated by build script
#CONFIG_BT_CTLR_PHY_2M=n
#CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
#CONFIG_ZMK_PM_SOFT_OFF=n
# Leader config, automated by build script
# CONFIG_ZMK_LEADER_MAX_SEQUENCES_PER_KEY=27
# CONFIG_ZMK_LEADER_MAX_KEYS_PER_SEQUENCE=2

CONFIG_BUILD_OUTPUT_UF2=n

