manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    - name: blank-slate-zmk-module
      remote: petejohanson
      revision: main
  self:
    path: config
